version: "3"

services:
  registry:
    image: fidedocker/registry
    container_name: registry
    networks:
      - beckn_network
    ports:
      - 3000:3000
      - 3030:3030
    restart: unless-stopped
    volumes:
      - registry_data_volume:/registry/overrideProperties/config
      - registry_database_volume:/registry/database

networks:
  beckn_network:
    driver: bridge

volumes:
  registry_data_volume:
    name: registry_data_volume
    external: true
  registry_database_volume:
    name: registry_database_volume
    external: true
